#!/bin/bash 
#PBS -N spE_p1_9 
#PBS -l select=1:ncpus=2:mem=60gb 
#PBS -l walltime=48:00:00 
#PBS -m ae 
#PBS -M qlegia@unsw.edu.au 
#PBS -J 0-10 

cd /home/z9701564/ElasticityQMC
echo 'I am now working on job ${PBS_ARRAY_INDEX}' 
conda init bash
source activate fenicsx-env
python3 sparse_qmc.py 10 ${PBS_ARRAY_INDEX} 1 
python3 sparse_qmc.py 10 ${PBS_ARRAY_INDEX} 2 
python3 sparse_qmc.py 10 ${PBS_ARRAY_INDEX} 3 
python3 sparse_qmc.py 10 ${PBS_ARRAY_INDEX} 4 
