#!/bin/bash 
#PBS -N E_p65_68 
#PBS -l select=1:ncpus=2:mem=10gb 
#PBS -l walltime=24:00:00 
#PBS -m ae 
#PBS -M qlegia@unsw.edu.au 
#PBS -J 0-15 

cd /home/z9701564/ElasticityQMC 
echo 'I am now working on job ${PBS_ARRAY_INDEX}' 
conda init bash
source activate fenicsx-env
python3 sparse_qmc.py 15 ${PBS_ARRAY_INDEX} 65
python3 sparse_qmc.py 15 ${PBS_ARRAY_INDEX} 66
python3 sparse_qmc.py 15 ${PBS_ARRAY_INDEX} 67
python3 sparse_qmc.py 15 ${PBS_ARRAY_INDEX} 68
